version: "3.7"

services:
  kiwix:
    image: ghcr.io/kiwix/kiwix-serve:3.8.1@sha256:9dbbc25fb8a4e9daa01aa5f8305220acd745ef46ebaf24044659405c26d2a07a
    user: "1000:1000"
    restart: on-failure
    privileged: true
    ports:
      - 8898:8080
    volumes:
      - ${UMBREL_ROOT}/data/storage/kiwix:/data
    command: >
      /data/*.zim